version: '3.9'

services:

  migrator:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app
    volumes:
      - ./Backend/src:/app
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
    depends_on:
      postgres:
        condition: service_healthy
    command: >-
      bash -lc '
        dotnet tool install -g dotnet-ef >/dev/null 2>&1 || true;
        /root/.dotnet/tools/dotnet-ef database update --project ShopMate.Persistence --context ShopMateDbContext
      '
  shopmate.api:
    build:
      context: ./Backend/src
      dockerfile: ShopMate.API/Dockerfile.dev
    container_name: api-dev
    ports:
      - "5000:80"
    volumes:
      - ./Backend/src:/app
    depends_on:
      - migrator
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Default=${CONNECTION_STRING}
    command: ["dotnet", "watch", "run", "--urls=http://0.0.0.0:80"]

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

volumes:
  pgdata:
